const datosPerajes = [
{ concesion: "CONCESIONARIA YUMA S.A.", nombre: "VALENCIA", servicioIP: "SI", tolisActivo: "SI", via: "Km 87 Vía Pueblo Nuevo – Valledupar", coordenadas: "10°15'34.9\"N 73°25'50.8\"W" },
{ concesion: "AUTOPISTAS RÍO GRANDE S.A.S.", nombre: "LA GÓMEZ", servicioIP: "NO", tolisActivo: "SI", via: "Km 37+300 Vía La Lizama – San Alberto", coordenadas: "7°23'50.9\"N 73°32'47.6\"W" },
{ concesion: "CONCESIONARIA YUMA S.A.", nombre: "LA LOMA", servicioIP: "SI", tolisActivo: "SI", via: "Km 42 Vía San Roque - Bosconia", coordenadas: "9°38'17.2\"N 73°38'21.9\"W" },
{ concesion: "AUTOPISTAS RÍO GRANDE S.A.S.", nombre: "PAILITAS", servicioIP: "SI", tolisActivo: "SI", via: "Km 28+500 Vía La Mata – San Roque", coordenadas: "8°51'11.0\"N 73°40'11.1\"W" },
{ concesion: "AUTOPISTAS DEL CARIBE S.A.S", nombre: "BAYUNCA", servicioIP: "SI", tolisActivo: "SI", via: "Km 03+450 RUTA 2511 -  vía Medellin - La Costa", coordenadas: "10°32'49.9\"N 75°21'54.3\"W" },
{ concesion: "AUTOPISTAS DEL CARIBE S.A.S", nombre: "GALAPA", servicioIP: "SI", tolisActivo: "SI", via: "Vía Cordialidad Km 98", coordenadas: "10°53'10.0\"N 74°50'41.0\"W" },
{ concesion: "CONCESIONARIA YUMA S.A.", nombre: "EL COPEY", servicioIP: "SI", tolisActivo: "SI", via: "Km 10+300 Vía Bosconia – Rio Ariguani", coordenadas: "10°03'37.7\"N 73°55'25.8\"W" },
{ concesion: "CONCESIÓN TRANSVERSAL DEL SISGA S.A.S.", nombre: "SAN LUIS DE GACENO", servicioIP: "SI", tolisActivo: "NO", via: "RWG8+6J San Luís de Gaceno, Boyacá", coordenadas: "4°49'32.6\"N 73°05'00.4\"W" },
{ concesion: "CONCESIÓN TRANSVERSAL DEL SISGA S.A.S.", nombre: "MACHETÁ", servicioIP: "SI", tolisActivo: "NO", via: "Vía Sisga – Guateque Km 27", coordenadas: "5°04'38.3\"N 73°33'12.3\"W" },
{ concesion: "CONCESIÓN VÍAS DEL NUS - VINUS S.A.S.", nombre: "TRAPICHE", servicioIP: "SI", tolisActivo: "SI", via: "Km 4  Vía alterna Girardota Hatillo", coordenadas: "6°23'58.6\"N 75°25'58.9\"W" },
{ concesion: "BTS CONCESIONARIO S.A.S.", nombre: "TUTA", servicioIP: "SI", tolisActivo: "SI", via: "Via Tunja – Paipa Km 12+200 Jurisdiccion Combita", coordenadas: "5°39'25.6\"N 73°16'42.2\"W" },
{ concesion: "APP GICA", nombre: "GUALANDAY", servicioIP: "SI", tolisActivo: "SI", via: "Km 9+0600 de la ruta 4004 vía Ibagué (Puente Blanco  El Espinal (cruce ruta 45))", coordenadas: "4°18'01.8\"N 75°03'00.3\"W" },
{ concesion: "VÍA 40", nombre: "CHUSACÁ", servicioIP: "SI", tolisActivo: "SI", via: "Soacha – Girardot Km 109", coordenadas: "4°32'15.1\"N 74°16'18.6\"W" },
{ concesion: "RUTA AL SUR", nombre: "ALTAMIRA", servicioIP: "SI", tolisActivo: "SI", via: "Vía Planeta Rica - Sincelejo Km 26 + 300", coordenadas: "2°08'34.4\"N 75°42'02.9\"W" },
{ concesion: "UT PEAJES NACIONALES", nombre: "LA ESPERANZA", servicioIP: "SI", tolisActivo: "SI", via: "Toluviego - Sincelejo", coordenadas: "9°25'50.9\"N 75°26'09.2\"W" },
{ concesion: "CONCESIÓN RUTA AL MAR SAS CORUMA S.A.S", nombre: "SAN ONOFRE", servicioIP: "SI", tolisActivo: "SI", via: "Vía San Onofre – Cruz del Viso Km 21+400 metros", coordenadas: "9°52'21.3\"N 75°23'36.6\"W" },
{ concesion: "CONCESIONARIA VIAL DEL PACÍFICO S.A.S - COVIPACÍFICO S.A.S", nombre: "AMAGÁ", servicioIP: "SI", tolisActivo: "NO", via: "KM 03+100 RUTA 6005 Via Santuario - Puerto Triunfo", coordenadas: "6°02'49.1\"N 75°39'35.9\"W" },
{ concesion: "BTS CONCESIONARIO S.A.S.", nombre: "EL ROBLE", servicioIP: "SI", tolisActivo: "SI", via: "Bogotá – Albarracín Km 36", coordenadas: "5°01'53.0\"N 73°50'23.8\"W" },
{ concesion: "CONCESIONARIA YUMA S.A.", nombre: "EL DIFÍCIL", servicioIP: "SI", tolisActivo: "SI", via: "KM 67+300 Plato – Pueblo Nuevo", coordenadas: "9°51'02.2\"N 74°14'10.9\"W" },
{ concesion: "CONCESIÓN RUTA AL MAR SAS CORUMA S.A.S", nombre: "LOS CEDROS", servicioIP: "SI", tolisActivo: "SI", via: "Via Puerto Rey – Montería Km 47 Recorrido  67 KMS", coordenadas: "8°49'56.0\"N 76°03'02.0\"W" },
{ concesion: "CONCESIÓN VÍAS DEL NUS - VINUS S.A.S.", nombre: "PANDEQUESO", servicioIP: "SI", tolisActivo: "SI", via: "KM 38+700 RUTA 2510 -  vía Medellín – La costa", coordenadas: "6°31'40.2\"N 75°23'45.7\"W" },
{ concesion: "AUTOPISTA DEL CAFÉ", nombre: "COROZAL", servicioIP: "SI", tolisActivo: "SI", via: "Vía La Paila - Armenia Km 23", coordenadas: "4°24'29.2\"N 75°53'59.8\"W" },
{ concesion: "RUTA MAGDALENA - SIERRA MAR", nombre: "TASAJERA", servicioIP: "SI", tolisActivo: "SI", via: "KM 50 Vía Barranquilla – Santa Marta", coordenadas: "10°58'37.9\"N 74°20'11.8\"W" },
{ concesion: "CONCESIONARIA VIAL DE ORIENTE S.A.S.", nombre: "VERACRUZ", servicioIP: "SI", tolisActivo: "SI", via: "Vía Cumaral – Paratebueno Km 29+555", coordenadas: "4°15'40.5\"N 73°26'53.3\"W" },
{ concesion: "RUTA MAGDALENA - SIERRA MAR", nombre: "LAUREANO GÓMEZ (PUENTE LAUREANO)", servicioIP: "SI", tolisActivo: "SI", via: "KM 3+300 Vía Barranquilla – Santa Marta", coordenadas: "10°58'43.5\"N 74°43'46.9\"W" },
{ concesion: "AUTOVIA NEIVA GIRARDOT S.A.S", nombre: "FLANDES", servicioIP: "SI", tolisActivo: "NO", via: "Km. 4 Vía Espinal - Girardot", coordenadas: "4°11'32.6\"N 74°51'40.1\"W" },
{ concesion: "CONCESIÓN PACIFICO TRES S.A.S", nombre: "ACAPULCO", servicioIP: "SI", tolisActivo: "SI", via: "Vía Y de Cerritos  - Cauyá PR2507 Km 24", coordenadas: "4°59'57.6\"N 75°51'31.8\"W" },
{ concesion: "CONCESIONARIA VIAL MONTES DE MARÍA S.A.S.", nombre: "EL CARMEN (CARMEN DE BOLÍVAR)", servicioIP: "NO", tolisActivo: "NO", via: "Km 70+500 Troncal de Occidente Ruta 2515 Vía Sincelejo – Calamar", coordenadas: "9°40'55.6\"N 75°07'29.6\"W" },
{ concesion: "PERIMETRAL ORIENTAL DE BOGOTÁ (POB)", nombre: "LA CABAÑA", servicioIP: "SI", tolisActivo: "SI", via: "La Calera – Briceño Km 21+800", coordenadas: "4°48'31.3\"N 73°56'44.8\"W" },
{ concesion: "PERIMETRAL ORIENTAL DE BOGOTÁ (POB)", nombre: "LOS PATIOS", servicioIP: "SI", tolisActivo: "SI", via: "La Calera – Briceño Km 0+050", coordenadas: "4°39'49.0\"N 74°00'38.1\"W" },
{ concesion: "UT PEAJES NACIONALES", nombre: "EL KORÁN", servicioIP: "SI", tolisActivo: "SI", via: " Bogotá – Medellín - Norte", coordenadas: "5°29'50.0\"N 74°36'48.8\"W" },
{ concesion: "CONCESION VIAL DE LOS LLANOS S.A.S.", nombre: "OCOA", servicioIP: "SI", tolisActivo: "NO", via: "Vía Villavicencio – Granada Km 54+450", coordenadas: "4°01'35.0\"N 73°46'30.8\"W" },
{ concesion: "AUTOVIA NEIVA GIRARDOT S.A.S", nombre: "NEIVA", servicioIP: "SI", tolisActivo: "NO", via: "Vía Neiva – Castilla Km 3+700 Jurisdicción Municipio de Neiva", coordenadas: "2°58'40.3\"N 75°18'26.5\"W" },
{ concesion: "CONCESIÓN COSTERA CARTAGENA BARRANQUILLA S.A.S", nombre: "PAPIROS", servicioIP: "SI", tolisActivo: "NO", via: "Vía al mar Km 101", coordenadas: "11°00'46.8\"N 74°53'22.4\"W" },
{ concesion: "CONCESIÓN LA PINTADA S.A.S", nombre: "LA PINTADA", servicioIP: "SI", tolisActivo: "SI", via: "Km 12+700 vía doble calzada La Pintada – Bolombolo", coordenadas: "5°48'44.9\"N 75°40'45.2\"W" },
{ concesion: "CONCESIÓN LA PINTADA S.A.S", nombre: "PRIMAVERA", servicioIP: "SI", tolisActivo: "SI", via: "Km 38+830 vía Primavera – Santa Bárbara – La Pintada", coordenadas: "5°58'07.0\"N 75°35'38.7\"W" },
{ concesion: "RUTA AL SUR", nombre: "LABERINTO", servicioIP: "SI", tolisActivo: "SI", via: "GFVX+35J Hobo, Huila", coordenadas: "2°32'33.7\"N 75°30'07.6\"W" },
{ concesion: "RUTA AL SUR", nombre: "LOS CAUCHOS", servicioIP: "SI", tolisActivo: "SI", via: "Vía Garzon – Neiva Km 98+499 Jurisdicción Municipio de Rivera", coordenadas: "2°47'09.2\"N 75°18'06.7\"W" },
{ concesion: "CONCESION VIAL DE LOS LLANOS S.A.S.", nombre: "YUCAO", servicioIP: "SI", tolisActivo: "NO", via: "Vía Puerto López - Puerto Gaitán Km.99+200", coordenadas: "4°21'04.8\"N 72°10'09.1\"W" },
{ concesion: "ACCENORTE", nombre: "UNISABANA", servicioIP: "SI", tolisActivo: "SI", via: "Km 5+600 Bogotá – Albarracín", coordenadas: "4°51'20.5\"N 74°01'52.8\"W" },
{ concesion: "AUTOPISTA DEL CAFÉ", nombre: "CIRCASIA", servicioIP: "SI", tolisActivo: "SI", via: "Vía Armenia - Pereira Km. 16+750", coordenadas: "4°41'55.0\"N 75°36'22.2\"W" },
{ concesion: "UT PEAJES NACIONALES", nombre: "LAS FLORES MORROA", servicioIP: "SI", tolisActivo: "SI", via: "Sincelejo-Puerta de Hierro-Calamar", coordenadas: "9°19'07.9\"N 75°19'11.9\"W" },
{ concesion: "CONCESIÓN SABANA DE OCCIDENTE S.A.S.", nombre: "CAIQUERO", servicioIP: "SI", tolisActivo: "SI", via: "Vía Cauyá - El Palo", coordenadas: "5°03'56.2\"N 74°24'51.4\"W" },
{ concesion: "AUTOPISTA DEL CAFÉ", nombre: "SAN BERNARDO (TRINIDAD ll)", servicioIP: "SI", tolisActivo: "SI", via: "Tres Puertas – Puente La Libertad Km. 9 + 200", coordenadas: "5°03'08.3\"N 75°35'40.6\"W" },
{ concesion: "AUTOPISTA DEL CAFÉ", nombre: "TARAPACÁ I", servicioIP: "SI", tolisActivo: "SI", via: "Vía Pereira – Manizales Km. 20 + 200", coordenadas: "4°56'23.8\"N 75°36'59.6\"W" },
{ concesion: "ACCENORTE", nombre: "FUSCA", servicioIP: "SI", tolisActivo: "SI", via: "Bogotá – Albarracín Km 4", coordenadas: "4°50'07.0\"N 74°01'44.1\"W" },
{ concesion: "AUTOPISTAS DEL CARIBE S.A.S", nombre: "SABANAGRANDE", servicioIP: "SI", tolisActivo: "SI", via: "Vía Oriental Km 55", coordenadas: "10°47'59.1\"N 74°45'32.6\"W" },
{ concesion: "CONCESION VIAL DE LOS LLANOS S.A.S.", nombre: "CASETABLA", servicioIP: "SI", tolisActivo: "NO", via: "Puerto López, Meta", coordenadas: "4°06'45.7\"N 72°50'05.1\"W" },
{ concesion: "DESARROLLO VIAL AL MAR S.A.S", nombre: "ABURRÁ", servicioIP: "SI", tolisActivo: "SI", via: "Oriente Occidente Km 39+600 Occidente Oriente Km 44+800 -  vía Santa Fe de Antioquia Medellín", coordenadas: "6°17'35.5\"N 75°39'03.8\"W" },
{ concesion: "CONCESIÓN VÍAS DEL NUS - VINUS S.A.S.", nombre: "CABILDO", servicioIP: "SI", tolisActivo: "SI", via: "Vía Ubate Puente Nacional  Km 66+200 Jurisdicción Saboyá", coordenadas: "6°23'45.0\"N 75°25'25.2\"W" },
{ concesion: "CONCESIÓN TÚNEL ABURRÁ - ORIENTE S.A", nombre: "TÚNEL DE ORIENTE", servicioIP: "SI", tolisActivo: "SI", via: "6CCV+CCQ Medellín, Antioquia", coordenadas: "6°13'15.9\"N 75°33'23.0\"W" },
{ concesion: "CONCESIÓN TÚNEL ABURRÁ - ORIENTE S.A", nombre: "VARIANTE LAS PALMAS", servicioIP: "SI", tolisActivo: "SI", via: "5GCC+9G Envigado, Antioquia", coordenadas: "6°10'16.1\"N 75°28'43.3\"W" },
{ concesion: "CONCESIÓN TÚNEL ABURRÁ - ORIENTE S.A", nombre: "SANTA ELENA", servicioIP: "SI", tolisActivo: "SI", via: "Km 21+500 - Vía Medellín - Ríonegro", coordenadas: "6°10'47.0\"N 75°27'40.8\"W" },
{ concesion: "AUTOPISTAS DEL CARIBE S.A.S", nombre: "TURBACO", servicioIP: "NO", tolisActivo: "SI", via: "Km 60+00 y 68+00 Ruta 9005 Troncal de Occidente", coordenadas: "10°21'25.7\"N 75°26'36.4\"W" },
{ concesion: "CONCESIONARIA VIAL ANDINA S.A.S. - COVIANDINA S.A.S", nombre: "PIPIRAL", servicioIP: "SI", tolisActivo: "SI", via: "Vía Villavicencio – Puente Susumuco Km 78+020", coordenadas: "4°12'00.5\"N 73°43'16.7\"W" },
{ concesion: "CONCESIONARIA DESARROLLO VIAL DE LA SABANA - DEVISAB", nombre: "RAMAL", servicioIP: "SI", tolisActivo: "SI", via: "kilómetro 106 Via Mosquera - Ramal a Soacha", coordenadas: "4°37'38.5\"N 74°17'24.0\"W" },
{ concesion: "CONCESIONARIA DESARROLLO VIAL DE LA SABANA - DEVISAB", nombre: "MONDOÑEDO", servicioIP: "SI", tolisActivo: "SI", via: "Vía Chía – La Mesa – Girardot Km 105 Jurisdicción del Municipio de Bojacá", coordenadas: "4°38'18.5\"N 74°17'38.2\"W" },
{ concesion: "CONCESIONARIA DESARROLLO VIAL DE LA SABANA - DEVISAB", nombre: "SAN PEDRO", servicioIP: "SI", tolisActivo: "SI", via: "Chía - La Mesa - Girardot Km.61 Jurisdicción del Municipio de la Mesa", coordenadas: "4°35'38.2\"N 74°29'11.7\"W" },
{ concesion: "ICCU", nombre: "NUEVO SALTO", servicioIP: "SI", tolisActivo: "SI", via: "Kilómetro 1.4 Vía Chusacá – El Triunfo – Viotá – El Portillo en la Vereda Charquito (Soacha)", coordenadas: "4°32'39.1\"N 74°16'06.9\"W" },
{ concesion: "ICCU", nombre: "AMOLADERO", servicioIP: "SI", tolisActivo: "SI", via: "V724+G8 Guatavita, Cundinamarca", coordenadas: "4°51'05.2\"N 73°44'39.2\"W" },
{ concesion: "ICCU", nombre: "LA BALSA", servicioIP: "SI", tolisActivo: "SI", via: "87G2+869 Lenguazaque, Cundinamarca", coordenadas: "5°19'32.8\"N 73°44'57.8\"W" },
{ concesion: "ICCU", nombre: "PACHO", servicioIP: "SI", tolisActivo: "SI", via: "3WQ9+HG8 Pacho, Cundinamarca", coordenadas: "5°05'20.0\"N 74°04'52.2\"W" },
{ concesion: "ICCU", nombre: "SAN MIGUEL", servicioIP: "SI", tolisActivo: "SI", via: "CMVX+M6H Sibaté, Cundinamarca", coordenadas: "4°26'39.1\"N 74°18'06.8\"W" },
{ concesion: "AUTOPISTA DEL CAFÉ", nombre: "TARAPACÁ II", servicioIP: "SI", tolisActivo: "SI", via: "Vía Pereira – Chinchiná PR29RSC Km 24 + 100", coordenadas: "4°57'00.9\"N 75°37'07.5\"W" },
{ concesion: "CONCESIONARIA PANAMERICANA S.A.", nombre: "JALISCO", servicioIP: "SI", tolisActivo: "SI", via: "Peaje Río Bogotá – Facatativá – Villeta – Vianí – Cambao Km 89+400 Jurisdicción del Municipio de Albán", coordenadas: "4°54'04.7\"N 74°25'34.0\"W" },
{ concesion: "INVÍAS", nombre: "PAJARITO", servicioIP: "SI", tolisActivo: "NO", via: "8CJ2+P64 Bello, Antioquia", coordenadas: "6°19'54.3\"N 75°35'57.9\"W" },
{ concesion: "CONCESIÓN COSTERA CARTAGENA BARRANQUILLA S.A.S", nombre: "MARAHUACO", servicioIP: "SI", tolisActivo: "NO", via: "Km 16 Vía Cartagena - Barranquilla", coordenadas: "10°34'29.3\"N 75°27'02.5\"W" },
{ concesion: "CONCESIONARIA VIAL ANDINA S.A.S. - COVIANDINA S.A.S", nombre: "BOQUERÓN I", servicioIP: "SI", tolisActivo: "SI", via: "Tramo que cubre:Vía Rincón Hondo - Agustín Codazzi", coordenadas: "4°27'09.4\"N 74°04'24.3\"W" },
{ concesion: "CONCESIONARIA DESARROLLO VIAL DE LA SABANA - DEVISAB", nombre: "LA TEBAIDA", servicioIP: "SI", tolisActivo: "SI", via: "Kilómetro 8 Vía Mosquera - Chía Jurisdicción del Municipio de Funza", coordenadas: "4°44'40.9\"N 74°10'16.9\"W" },
{ concesion: "CONCESIONARIA DESARROLLO VIAL DE LA SABANA - DEVISAB", nombre: "PUBENZA", servicioIP: "SI", tolisActivo: "SI", via: "Vía Chía – La Mesa – Girardot Km 16 Jurisdicción del Municipio de Tocaima", coordenadas: "4°24'12.2\"N 74°43'53.1\"W" },
{ concesion: "CONCESIONARIA YUMA S.A.", nombre: "TUCURINCA", servicioIP: "SI", tolisActivo: "SI", via: "KM 50 Rio Ariguani – Ye de Cienaga", coordenadas: "10°36'33.2\"N 74°10'06.3\"W" },
{ concesion: "AUTOPISTAS DEL CARIBE S.A.S", nombre: "GAMBOTE", servicioIP: "NO", tolisActivo: "SI", via: "Km 61+400 Ruta 9005 Troncal de Occidente", coordenadas: "10°08'11.1\"N 75°15'51.3\"W" },
{ concesion: "CONCESIONARIA AUTOPISTA MAGDALENA MEDIO S.A.S.", nombre: "ZAMBITO", servicioIP: "SI", tolisActivo: "SI", via: "Vía Rio Ermitaño La Lizama Km 6", coordenadas: "6°17'37.3\"N 74°27'27.5\"W" },
{ concesion: "CONCESIÓN RUTA AL MAR SAS CORUMA S.A.S", nombre: "PURGATORIO", servicioIP: "SI", tolisActivo: "SI", via: "Via Planeta Rica – Montería Km 32+500 Recorrido 49 KMS", coordenadas: "8°40'19.3\"N 75°47'53.5\"W" },
{ concesion: "CONCESION VIAL DE LOS LLANOS S.A.S.", nombre: "LA LIBERTAD", servicioIP: "SI", tolisActivo: "NO", via: "Vía Villavicencio – Puerto López Km 18+900", coordenadas: "4°03'25.2\"N 73°27'47.7\"W" },
{ concesion: "APP GICA", nombre: "CHICORAL", servicioIP: "SI", tolisActivo: "SI", via: "Km. 17+0350 de la ruta 4004B vía Variante de Chicoral", coordenadas: "4°14'44.2\"N 74°52'50.0\"W" },
{ concesion: "CONCESIONARIA VIAL DE ORIENTE S.A.S.", nombre: "PUENTE AMARILLO", servicioIP: "SI", tolisActivo: "SI", via: "Conexión Anillo vial Cumaral Km 7+135", coordenadas: "4°11'44.9\"N 73°35'40.1\"W" },
{ concesion: "PISA", nombre: "BETANIA", servicioIP: "SI", tolisActivo: "SI", via: "Km 14 Vía Aguasclaras – Ocaña", coordenadas: "3°58'19.6\"N 76°15'12.2\"W" },
{ concesion: "AUTOPISTA DEL CAFÉ", nombre: "SANTAGUEDA", servicioIP: "SI", tolisActivo: "SI", via: "Cruce Guayacanes – La Manuela Km 6", coordenadas: "5°02'55.9\"N 75°35'55.9\"W" },
{ concesion: "UNION VÍAL RÍO PAMPLONITA S.A.S.", nombre: "LOS ACACIOS", servicioIP: "SI", tolisActivo: "NO", via: "Km 119+900", coordenadas: "7°43'16.5\"N 72°34'17.4\"W" },
{ concesion: "DEVIMED S.A.", nombre: "COPACABANA", servicioIP: "SI", tolisActivo: "SI", via: "8FHM+5R Copacabana, Antioquia", coordenadas: "6°19'41.0\"N 75°30'55.9\"W" },
{ concesion: "DEVIMED S.A.", nombre: "LAS PALMAS", servicioIP: "SI", tolisActivo: "SI", via: "Km. 5 RUTA 5601 Vía Medellín - La Ceja", coordenadas: "6°09'02.7\"N 75°31'52.8\"W" },
{ concesion: "BTS CONCESIONARIO S.A.S.", nombre: "ALBARRACÍN", servicioIP: "SI", tolisActivo: "SI", via: "Vía Bogotá Tunja KM 82+200 - Jurisdicción Villa Pinzón (Cundinamarca)", coordenadas: "5°17'26.6\"N 73°35'00.5\"W" },
{ concesion: "CONCESIONARIA AUTOPISTA MAGDALENA MEDIO S.A.S.", nombre: "AGUAS NEGRAS", servicioIP: "SI", tolisActivo: "SI", via: "Vía Rio Ermitaño La Lizama Km 84", coordenadas: "6°38'42.8\"N 73°57'09.1\"W" },
{ concesion: "CONCESIÓN RUTA AL MAR SAS CORUMA S.A.S", nombre: "MATA DE CAÑA", servicioIP: "SI", tolisActivo: "SI", via: "Vía Monteria - Lorica Km 32+700 Metros", coordenadas: "9°05'28.8\"N 75°49'10.1\"W" },
{ concesion: "CONCESIÓN COSTERA CARTAGENA BARRANQUILLA S.A.S", nombre: "PUERTO COLOMBIA", servicioIP: "SI", tolisActivo: "NO", via: "Vía al Mar Km 93", coordenadas: "10°58'04.3\"N 74°57'21.9\"W" },
{ concesion: "CONCESIONARIA ALTERNATIVAS VIALES S.A.S", nombre: "HONDA", servicioIP: "SI", tolisActivo: "SI", via: "Km 35 + 100 Vía Mariquita – Honda", coordenadas: "5°12'05.7\"N 74°49'13.0\"W" },
{ concesion: "CONCESIONARIA YUMA S.A.", nombre: "PUENTE PLATO", servicioIP: "SI", tolisActivo: "SI", via: "KM 0+150 Vía Plata – Pueblo Nuevo", coordenadas: "9°47'29.4\"N 74°48'32.0\"W" },
{ concesion: "CONCESIÓN SABANA DE OCCIDENTE S.A.S.", nombre: "SIBERIA", servicioIP: "SI", tolisActivo: "SI", via: "Bogotá (El Cortijo) – Siberia – La Punta – El Vino – Villeta", coordenadas: "4°46'50.1\"N 74°11'06.2\"W" },
{ concesion: "CONCESIÓN RUTA AL MAR SAS CORUMA S.A.S", nombre: "LA APARTADA", servicioIP: "SI", tolisActivo: "SI", via: "Vía Caucasia – Planeta Rica Km 12", coordenadas: "8°01'52.7\"N 75°18'04.8\"W" },
{ concesion: "AUTOVIA NEIVA GIRARDOT S.A.S", nombre: "EL PATÁ", servicioIP: "SI", tolisActivo: "NO", via: "Vía Neiva – Castilla Km 54+400 Jurisdicción de Aipe", coordenadas: "3°23'33.8\"N 75°12'14.6\"W" },
{ concesion: "CONCESIÓN PACIFICO TRES S.A.S", nombre: "SUPÍA", servicioIP: "SI", tolisActivo: "SI", via: "Vía La Felisa – La Pintada", coordenadas: "5°32'27.6\"N 75°34'13.2\"W" },
{ concesion: "CONCESIONARIA VIAL MONTES DE MARÍA S.A.S.", nombre: "CALAMAR", servicioIP: "SI", tolisActivo: "NO", via: "Tramo que cubre:Vía Agustín Codazzi - San Diego", coordenadas: "10°12'29.3\"N 74°56'42.2\"W" },
{ concesion: "ACCENORTE", nombre: "ANDES", servicioIP: "SI", tolisActivo: "SI", via: "Sector Bogotá (calle 236)-Briceño", coordenadas: "4°49'48.9\"N 74°01'59.3\"W" },
{ concesion: "AUTOPISTA RIO MAGDALENA S.A", nombre: "VEGACHÍ", servicioIP: "SI", tolisActivo: "NO", via: "Tramo vial 4G que conecta el municipio de Vegachí con Remedios (Antioquia)", coordenadas: "6°37'37.0\"N 74°47'49.9\"W" },
{ concesion: "AUTOPISTA RIO MAGDALENA S.A", nombre: "PUERTO BERRÍO", servicioIP: "SI", tolisActivo: "NO", via: "Vía Alto de Dolores - Puerto Berrío", coordenadas: "6°29'48.5\"N 74°30'04.8\"W" },
{ concesion: "CONCESIONARIA VIAL DE ORIENTE S.A.S.", nombre: "SAN PEDRO", servicioIP: "SI", tolisActivo: "SI", via: "Villanueva - Monterrey Km.15+000", coordenadas: "4°40'43.2\"N 72°56'37.7\"W" },
{ concesion: "AUTOPISTA DEL CAFÉ", nombre: "PAVAS (TRINIDAD I)", servicioIP: "SI", tolisActivo: "SI", via: "Club Campestre – La Trinidad Km. 1 + 200", coordenadas: "5°01'38.1\"N 75°35'14.5\"W" },
{ concesion: "CONCESIÓN VÍAS DEL NUS - VINUS S.A.S.", nombre: "CISNEROS", servicioIP: "SI", tolisActivo: "SI", via: "KM 03+000 RUTA 6206. Via Cisneros - Puerto Berrio", coordenadas: "6°32'10.2\"N 75°04'32.6\"W" },
{ concesion: "CONCESIONARIA PANAMERICANA S.A.", nombre: "GUAYABAL", servicioIP: "SI", tolisActivo: "SI", via: "Peaje Rio Bogotá – Facatativa – Villeta – Viani – Cambao Km 63 Jurisdicción del Municipio de Guayabal", coordenadas: "4°53'00.4\"N 74°28'59.5\"W" },
{ concesion: "UT PEAJES NACIONALES", nombre: "EL CORZO", servicioIP: "SI", tolisActivo: "SI", via: "El Corzo - Madrid", coordenadas: "4°44'55.0\"N 74°17'28.1\"W" },
{ concesion: "UT PEAJES NACIONALES", nombre: "EL PICACHO", servicioIP: "NO", tolisActivo: "SI", via: "Bucaramanga - Pamplona", coordenadas: "7°06'28.8\"N 72°58'08.1\"W" },
{ concesion: "UT PEAJES NACIONALES", nombre: "GARZONES I", servicioIP: "SI", tolisActivo: "SI", via: "Vía Monteria - Lorica Km. 1 más 320 metros", coordenadas: "8°50'42.7\"N 75°49'28.4\"W" },
{ concesion: "CONCESION VIAL DE LOS LLANOS S.A.S.", nombre: "IRACÁ", servicioIP: "SI", tolisActivo: "NO", via: "Vía Villavicencio – Granada Km 7+200", coordenadas: "3°37'58.5\"N 73°42'23.2\"W" },
{ concesion: "CONCESIONARIA VIAL ANDINA S.A.S. - COVIANDINA S.A.S", nombre: "BOQUERÓN II", servicioIP: "SI", tolisActivo: "SI", via: "Vía Rio Negro – San Alberto Km 53+100", coordenadas: "4°27'15.2\"N 74°03'00.3\"W" },
{ concesion: "UT PEAJES NACIONALES", nombre: "RÍO BOGOTÁ", servicioIP: "SI", tolisActivo: "SI", via: "Fontibon - Mosquera", coordenadas: "4°41'54.5\"N 74°10'45.9\"W" },
{ concesion: "CONCESIÓN RUTA AL MAR SAS CORUMA S.A.S", nombre: "LOS MANGUITOS", servicioIP: "SI", tolisActivo: "SI", via: "Vía Caucasia – Planeta Rica (Municipio de Plaza Bonita) Cubre Tramo Buenavista – Planeta Rica", coordenadas: "8°18'13.2\"N 75°31'53.9\"W" },
{ concesion: "UNIÓN VIAL CAMINO DEL PACIFICO S.A.S", nombre: "LOBOGUERRERO", servicioIP: "SI", tolisActivo: "SI", via: "VÍA BUENAVENTURA - BUGA KM 63+700 Tramo que cubre: Desde el PR 63+310 en Loboguerrero y finaliza en el PR 118+418 en Buga", coordenadas: "3°45'46.8\"N 76°39'56.1\"W" },
{ concesion: "CONCESIONARIA ALTERNATIVAS VIALES S.A.S", nombre: "ALVARADO", servicioIP: "SI", tolisActivo: "SI", via: "Vía Andalucía – Y de Cerritos PR2506 Km 86", coordenadas: "4°30'28.1\"N 74°59'30.2\"W" },
{ concesion: "CONCESIÓN ALTO MAGDALENA S.A.S", nombre: "CAMBAO", servicioIP: "SI", tolisActivo: "SI", via: "VÍA BUCARAMANGA - SAN GIL", coordenadas: "4°56'46.6\"N 74°43'09.2\"W" },
{ concesion: "PISA", nombre: "LA URIBE", servicioIP: "SI", tolisActivo: "SI", via: "Vía Andalucía – Cerritos Km 12+300", coordenadas: "4°15'11.0\"N 76°07'05.3\"W" },
{ concesion: "VÍA 40", nombre: "CHINAUTA", servicioIP: "SI", tolisActivo: "SI", via: "Soacha – Girardot Km 52", coordenadas: "4°16'10.1\"N 74°30'00.1\"W" },
{ concesion: "AUTOPISTAS RÍO GRANDE S.A.S.", nombre: "MORRISON", servicioIP: "SI", tolisActivo: "SI", via: "Km 28+500 Vía San Alberto – Aguaclara", coordenadas: "8°05'32.9\"N 73°33'36.4\"W" },
{ concesion: "CONCESIONARIA VIAL ANDINA S.A.S. - COVIANDINA S.A.S", nombre: "NARANJAL", servicioIP: "SI", tolisActivo: "SI", via: "Caqueza – Guayabetal Km 44+700", coordenadas: "4°16'48.4\"N 73°50'05.2\"W" },
{ concesion: "UT PEAJES NACIONALES", nombre: "GARZONES II", servicioIP: "SI", tolisActivo: "SI", via: "Vía Monteria - Lorica Km. 1 más 320 metros", coordenadas: "8°49'40.6\"N 75°50'13.5\"W" },
{ concesion: "AUTOPISTAS DEL CARIBE S.A.S", nombre: "PASACABALLOS", servicioIP: "NO", tolisActivo: "SI", via: "Variante de Gambote", coordenadas: "10°14'41.1\"N 75°26'44.8\"W" },
{ concesion: "RUTAS DEL VALLE", nombre: "ESTAMBUL", servicioIP: "SI", tolisActivo: "SI", via: "Vía Cali – Andalucía Km 5", coordenadas: "3°30'02.7\"N 76°26'34.9\"W" },
{ concesion: "RUTAS DEL VALLE", nombre: "CIAT", servicioIP: "SI", tolisActivo: "SI", via: "Vía Cali – Andalucía Km 17+300", coordenadas: "3°31'24.5\"N 76°20'35.7\"W" },
{ concesion: "RUTAS DEL VALLE", nombre: "PASO DE LA TORRE", servicioIP: "SI", tolisActivo: "SI", via: "Vía Vijes – Rozo Km 1+500", coordenadas: "3°37'39.6\"N 76°27'27.6\"W" },
{ concesion: "RUTAS DEL VALLE", nombre: "CENCAR", servicioIP: "SI", tolisActivo: "SI", via: "Vía Yumbo – Aeropuerto Km 2+950", coordenadas: "3°33'26.5\"N 76°27'45.9\"W" },
{ concesion: "RUTAS DEL VALLE", nombre: "CERRITO", servicioIP: "SI", tolisActivo: "SI", via: "Vía Cali - Andalucia Km 43+200", coordenadas: "3°42'47.1\"N 76°19'10.1\"W" },
{ concesion: "RUTAS DEL VALLE", nombre: "MEDIACANOA", servicioIP: "SI", tolisActivo: "SI", via: "Vía Cali – Mediacanoa Km 36+600", coordenadas: "3°45'35.1\"N 76°24'40.6\"W" },
{ concesion: "RUTAS DEL VALLE", nombre: "VILLARICA", servicioIP: "SI", tolisActivo: "SI", via: "Kilometro 91 Vía Panamericana Jurisdicción del Municipio de Villa Rica", coordenadas: "3°09'04.4\"N 76°27'36.2\"W" },
{ concesion: "RUTAS DEL VALLE", nombre: "ROZO", servicioIP: "SI", tolisActivo: "SI", via: "Vía Palmaseca - Cerrito Km 17", coordenadas: "3°38'38.2\"N 76°22'51.8\"W" },
{ concesion: "CONCESIÓN ALTO MAGDALENA S.A.S", nombre: "GUATAQUÍ", servicioIP: "SI", tolisActivo: "SI", via: "Km 3 Ruta 45", coordenadas: "4°33'51.3\"N 74°47'51.0\"W" },
{ concesion: "CONCESIÓN RUTA AL MAR SAS CORUMA S.A.S", nombre: "SAN CARLOS", servicioIP: "SI", tolisActivo: "SI", via: "Vía Montería - San Carlos ubicado sobre el Km - 9+700", coordenadas: "8°42'36.8\"N 75°43'00.0\"W" },
{ concesion: "THOMAS INSTRUMENTS S.A.", nombre: "LEBRIJA", servicioIP: "SI", tolisActivo: "NO", via: "Vía Fortuna - Bucaramanga Km 65+500 Jurisdicción del municipuio de Lebrija", coordenadas: "7°06'12.0\"N 73°11'06.7\"W" },
{ concesion: "CONCESIÓN ALTO MAGDALENA S.A.S", nombre: "BRISAS", servicioIP: "SI", tolisActivo: "SI", via: "Vía Mediacanoa - Ansermanuevo Km 13", coordenadas: "5°27'26.1\"N 74°38'22.7\"W" },
{ concesion: "PERIMETRAL ORIENTAL DE BOGOTÁ (POB)", nombre: "SOPÓ", servicioIP: "SI", tolisActivo: "SI", via: "El Salitre - Sopó", coordenadas: "4°50'30.8\"N 73°56'10.0\"W" },
{ concesion: "CONCESIÓN COSTERA CARTAGENA BARRANQUILLA S.A.S", nombre: "JUAN MINA", servicioIP: "SI", tolisActivo: "NO", via: "Vía La Cordialidad - Galapa", coordenadas: "10°55'46.2\"N 74°53'40.1\"W" },
{ concesion: "CONCESIONARIA RUTA DEL CACAO S.A.S.", nombre: "LA LIZAMA", servicioIP: "SI", tolisActivo: "SI", via: "La Lizama", coordenadas: "7°05'01.3\"N 73°43'03.5\"W" },
{ concesion: "APP GICA", nombre: "COCORA", servicioIP: "SI", tolisActivo: "SI", via: "Km. 13+750 variante de la Segunda Calzada Ibagué – Cajamarca", coordenadas: "4°24'22.7\"N 75°17'01.7\"W" },
{ concesion: "CONCESIÓN COSTERA CARTAGENA BARRANQUILLA S.A.S", nombre: "GALAPA MALAMBO", servicioIP: "SI", tolisActivo: "NO", via: "Km 12+700", coordenadas: "10°53'12.3\"N 74°50'38.0\"W" },
{ concesion: "CONCESIÓN PACIFICO TRES S.A.S", nombre: "IRRA", servicioIP: "SI", tolisActivo: "SI", via: "787R+2F Neira, Caldas", coordenadas: "5°15'46.0\"N 75°39'31.5\"W" },
{ concesion: "CONCESIÓN PACIFICO TRES S.A.S", nombre: "GUAICO", servicioIP: "SI", tolisActivo: "SI", via: "464Q+8W Risaralda, Caldas", coordenadas: "5°06'21.9\"N 75°45'36.6\"W" },
{ concesion: "UT PEAJES NACIONALES", nombre: "SAN JUAN", servicioIP: "SI", tolisActivo: "SI", via: "Ubicación: 61+400 Tramo que cubre:Vía La Paz – Distracción", coordenadas: "10°47'59.9\"N 72°58'31.6\"W" },
{ concesion: "UT PEAJES NACIONALES", nombre: "SAN DIEGO", servicioIP: "SI", tolisActivo: "SI", via: "Tramo que cubre:Vía Aguztín Codazzi - San Diego", coordenadas: "10°07'18.6\"N 73°14'19.1\"W" },
{ concesion: "UT PEAJES NACIONALES", nombre: "RINCÓN HONDO", servicioIP: "SI", tolisActivo: "SI", via: "Tramo que cubre:Vía Rincón Hondo - Agustín Codazzi", coordenadas: "9°25'50.8\"N 73°28'25.0\"W" },
{ concesion: "UT PEAJES NACIONALES", nombre: "CARIMAGUA", servicioIP: "SI", tolisActivo: "SI", via: "Vía Planeta Rica - Sincelejo Km 26 + 300", coordenadas: "8°36'17.7\"N 75°29'05.3\"W" },
{ concesion: "UT PEAJES NACIONALES", nombre: "TARAZÁ", servicioIP: "SI", tolisActivo: "SI", via: "KM 01+200 RUTA 2512 - Via Medellin - La Costa", coordenadas: "7°34'59.5\"N 75°23'59.9\"W" },
{ concesion: "UT PEAJES NACIONALES", nombre: "LOS LLANOS", servicioIP: "SI", tolisActivo: "SI", via: "KM 03+450 RUTA 2511 - vía Medellin - La Costa", coordenadas: "6°49'49.9\"N 75°28'05.7\"W" },
{ concesion: "UT PEAJES NACIONALES", nombre: "RÍO BLANCO", servicioIP: "SI", tolisActivo: "SI", via: "Rio Negro – San Alberto", coordenadas: "7°33'15.5\"N 73°13'52.0\"W" },
{ concesion: "UT PEAJES NACIONALES", nombre: "PLATANAL", servicioIP: "SI", tolisActivo: "SI", via: "Km 14 Vía Aguasclaras – Ocaña", coordenadas: "8°13'51.5\"N 73°29'55.0\"W" },
{ concesion: "UT PEAJES NACIONALES", nombre: "LA PARADA", servicioIP: "SI", tolisActivo: "SI", via: "Km. 2 de la Autopista Internacional que comunica a Cúcuta con San Antonio", coordenadas: "7°52'03.0\"N 72°29'03.3\"W" },
  { concesion: "UT PEAJES NACIONALES", nombre: "CANO", servicioIP: "SI", tolisActivo: "SI", via: "San Juan de Pasto - Cano", coordenadas: "1°25'31.7\"N 77°17'04.0\"W" },
  { concesion: "UT PEAJES NACIONALES", nombre: "TORO", servicioIP: "SI", tolisActivo: "SI", via: "Mediacanoa - Ansermanuevo", coordenadas: "4°39'55.6\"N 76°02'58.3\"W" },
  { concesion: "UT PEAJES NACIONALES", nombre: "CERRITOS II", servicioIP: "SI", tolisActivo: "SI", via: "Vía Andalucía – Y de Cerritos PR2506 Km 86", coordenadas: "4°47'36.2\"N 75°51'35.9\"W" },
  { concesion: "UT PEAJES NACIONALES", nombre: "TÚNEL DE LA LÍNEA QUINDÍO", servicioIP: "SI", tolisActivo: "SI", via: "Calarcá - Cajamarca", coordenadas: "4°31'26.2\"N 75°35'21.4\"W" },
  { concesion: "UT PEAJES NACIONALES", nombre: "TÚNEL DE LA LÍNEA TOLIMA", servicioIP: "SI", tolisActivo: "SI", via: "Armenia - Ibague", coordenadas: "4°26'42.8\"N 75°31'06.0\"W" },
  { concesion: "AUTOPISTAS DEL NORDESTE S.A.S", nombre: "LA FRAGUA", servicioIP: "SI", tolisActivo: "SI", via: "Km. 33+400 de la vía entre Remedios y Zaragoza (Antioquia)", coordenadas: "7°16'38.6\"N 74°49'55.4\"W" },
  { concesion: "AUTOPISTAS DEL NORDESTE S.A.S", nombre: "ZARAGOZA", servicioIP: "SI", tolisActivo: "SI", via: "Km. 21+300 de la vía que conecta el municipio de Zaragoza con Caucasia (Antioquia - Zaragoza)", coordenadas: "7°38'01.5\"N 74°53'40.5\"W" },
  { concesion: "CONCESIONARIA VIAL UNION DEL SUR S.A.S.", nombre: "EL PLACER", servicioIP: "SI", tolisActivo: "SI", via: "Nariño - Tangua", coordenadas: "1°03'50.1\"N 77°25'41.7\"W" },
  { concesion: "UT PEAJES NACIONALES", nombre: "BICENTENARIO", servicioIP: "SI", tolisActivo: "SI", via: "Villeta - Puerto Salgar", coordenadas: "5°12'11.2\"N 74°41'04.5\"W" },
  { concesion: "UT PEAJES NACIONALES", nombre: "SABOYÁ", servicioIP: "SI", tolisActivo: "SI", via: "Vía Ubate Puente Nacional  Km 66+200 Jurisdicción Saboyá", coordenadas: "5°43'40.5\"N 73°44'40.8\"W" },
  { concesion: "UT PEAJES NACIONALES", nombre: "PUERTO TRIUNFO", servicioIP: "SI", tolisActivo: "SI", via: "KM 130+100 RUTA 6005 Autopista  Medellin - Bogota", coordenadas: "5°52'21.3\"N 74°36'40.8\"W" },
  { concesion: "UT PEAJES NACIONALES", nombre: "COCORNA", servicioIP: "SI", tolisActivo: "SI", via: "KM 03+100 RUTA 6005 Via Santuario - Puerto Triunfo", coordenadas: "6°07'28.7\"N 75°14'35.0\"W" },
  { concesion: "UT PEAJES NACIONALES", nombre: "OIBA", servicioIP: "NO", tolisActivo: "SI", via: "Vía Puente Nacional – San Gil Km 62+950", coordenadas: "6°10'41.5\"N 73°19'59.8\"W" },
  { concesion: "UT PEAJES NACIONALES", nombre: "CURITÍ", servicioIP: "SI", tolisActivo: "SI", via: "San Gil - Aratoca", coordenadas: "6°37'03.2\"N 73°04'49.4\"W" },
  { concesion: "UT PEAJES NACIONALES", nombre: "EL CRUCERO", servicioIP: "SI", tolisActivo: "SI", via: "Via Sogamoso Yopal Km 8+900  Jurisdiccion Sogamoso", coordenadas: "5°37'54.9\"N 72°55'16.8\"W" },
  { concesion: "UT PEAJES NACIONALES", nombre: "ARCABUCO", servicioIP: "SI", tolisActivo: "SI", via: "Barbosa - Tunja", coordenadas: "5°47'41.8\"N 73°28'39.6\"W" },
  { concesion: "UT PEAJES NACIONALES", nombre: "SÁCHICA", servicioIP: "SI", tolisActivo: "SI", via: "Vía Chiquinquirá Tunja km 42+800 Jurisdicción Sáchica", coordenadas: "5°33'28.0\"N 73°30'04.4\"W" },
  { concesion: "INVÍAS", nombre: "CASABLANCA", servicioIP: "SI", tolisActivo: "NO", via: "Cogua – Tausa Km 40+000", coordenadas: "5°06'15.3\"N 73°54'46.4\"W" },
  { concesion: "UT PEAJES NACIONALES", nombre: "LOS CUROS", servicioIP: "SI", tolisActivo: "SI", via: "Aratoca - Bucaramanga", coordenadas: "6°49'32.2\"N 72°59'59.7\"W" },
  { concesion: "UT PEAJES NACIONALES", nombre: "SAN CLEMENTE", servicioIP: "SI", tolisActivo: "SI", via: "Vía Cauyá - El Palo", coordenadas: "5°19'56.9\"N 75°46'31.9\"W" },
  { concesion: "UT PEAJES NACIONALES", nombre: "RÍO FRÍO", servicioIP: "SI", tolisActivo: "SI", via: "Mediacanoa - Ansermanuevo", coordenadas: "3°59'43.4\"N 76°19'42.7\"W" },
  { concesion: "AUTOPISTAS URABÁ S.A.S.", nombre: "FUEMIA", servicioIP: "SI", tolisActivo: "SI", via: "Km 24+35, Dabeiba, Antioquia", coordenadas: "6°57'01.3\"N 76°14'37.2\"W" },
  { concesion: "AUTOPISTAS URABÁ S.A.S.", nombre: "MUTATÁ", servicioIP: "SI", tolisActivo: "SI", via: "Dabeiba, Antioquia", coordenadas: "7°13'20.2\"N 76°26'00.4\"W" },
  { concesion: "INSTITUTO FINANCIERO PARA EL DESARROLLO DE SANTANDER - IDESAN", nombre: "LA PUNTA", servicioIP: "SI", tolisActivo: "NO", via: "WX98+275 Piedecuesta, Santander", coordenadas: "6°55'03.0\"N 73°02'03.3\"W" },
  { concesion: "RUTA PORTUARIA (S.F CONVIAS)", nombre: "BARRANQUILLITA", servicioIP: "SI", tolisActivo: "SI", via: "X6PH+H67 Barranquilla, Atlántico", coordenadas: "10°59'11.1\"N 74°46'19.1\"W" },
  { concesion: "RUTA PORTUARIA (S.F CONVIAS)", nombre: "ZONA FRANCA", servicioIP: "SI", tolisActivo: "SI", via: "X64M+4MF Barranquilla, Atlántico", coordenadas: "10°57'19.1\"N 74°45'57.0\"W" },
  { concesion: "SECRETARÍA DE MOVILIDAD DE ENVIGADO", nombre: "ESCOBERO", servicioIP: "SI", tolisActivo: "SI", via: "4FVF+MW, Loma Del Escobero, Envigado, Vda. El Penasco, Envigado, Antioquia", coordenadas: "6°08'35.6\"N 75°31'28.9\"W" }
];
